blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/vikrantblu/marathi_tts/discussions
    about: Ask general questions, request advice, or chat with the community.
  - name: Security Vulnerability Reporting
    url: https://github.com/vikrantblu/marathi_tts/security/advisories/new
    about: Privately report security vulnerabilities.
